### ISSUE TITLE
Peak-valley RSA?

### ISSUE THREAD

**Issue by AnteriorInsula** [neuropsychology/NeuroKit.py#15]
Hi!  Thanks for providing this toolkit.

I have a question about the way NeuroKit can score RSA (and I'm very new to Python as well as psychophysiology, so I apologize if the answer to this question is overly obvious).  Because of the short interval over which I'm recording ECG (30 seconds per epoch), I'd like to use the peak-valley method to score RSA (as per Eckberg, 1983: http://jap.physiology.org/content/jap/54/4/961.full.pdf).  Is there a way to do this in NeuroKit?

Many thanks!

Ellie

**Comment by DominiqueMakowski** [comment]
@AnteriorInsula My main reference when I built the RSA function was [Lewis 2012](https://www.ncbi.nlm.nih.gov/pubmed/22138367) that compares three methods, i.e. the peak-to-through (P2T), the High Frequency Heart Rate Variability (HF) and the Porges–Bohrer method. 

Altough the latter presented several advantages, I did not manage do implement it yet (as I'm not an expert in signal processing). The HF is implemented in the [`ecg_hrv`](http://neurokit.readthedocs.io/en/latest/documentation.html#ecg-hrv) function (and is suitable for epochs of 30s) but returns a single index (e.g., "over your 30 s epoch, the estimated RSA is 12.1"). [`ecg_rsa`](http://neurokit.readthedocs.io/en/latest/documentation.html#ecg-rsa), on the other hand, implements the P2T method. Assuming a respiratory signal is provided, it basically substracts the max RR interval from the minimum RR interval, **within each respiratory cycle** (note that Biopac's apparently doing the [same thing](https://www.biopac.com/?app-advanced-feature=respiratory-sinus-arrhythmia-rsa-analysis)). This gives a continuous RSA signal that can be found in the main dataframe after applying the `ecg_process` routine.

Now, as to the peak-valley method, I carefully read the paper you provided. Unfortunately (*altough maybe it's because it's morning and the heat here in Paris is already liquefying my brain*), I did not quite understand what exactly this method refers to. The author speaks a lot about the PP interval, which corresponds to the RR interval. So either he used the RR interval (which continuous (interpolated and corrected) signal is computed with `ecg_hrv` and `ecg_process`) as an index of RSA, or I missed something. If that's the case, please enlight me about his procedure.

However, as this paper is rather old, I would suggest a use of a more recent method for estimating RSA. If you have specific reasons why to use another method, please let me know, we could try implement it.

Anyway, good luck with python (it's woth the time) and neurokit, and do not hesitate to ask anything 😉
