### ISSUE TITLE
How to find non-responders for EDA?

### ISSUE THREAD

**Issue by Eichhof** [neuropsychology/NeuroKit.py#45]
Hi there,

I have read that around 5% of the people are non-responders for EDA. How can they be identified (and removed from the experiment)? I'm thinking about looking at the number of peaks (a person who has almost no peaks after a stimulus might be a non-responder).

**Comment by DominiqueMakowski** [comment]
There are, indeed, some people which autonomic responses are harder to measure. The proportion can vary (due to the quality of your aquisition device, their skin thickness, autonomic regulation or any other things you could think of). 

One possibility is to keep them in the analyses. They should indeed, respond (non-respond, in that case) similarly in all conditions, adding uniformly distributed variance. 

Another possibility is to chose a way to remove them. I do not know about the existence of "official" guidelines to detect them. I guess you could measure the number of peaks in a baseline period, and remove all the people which number of peaks is lower than a particular treshold. Or remove the people that had no SCR in the conditions of your experiment?

The important thing is here, for whatever solution you chose, to explicitly explain it in your report/paper.

Let us know what worked best 😉
